# Generated by Django 5.2.4 on 2025-07-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='автор')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='blog.category', verbose_name='Категория')),
                ('name', models.ManyToManyField(blank=True, null=True, related_name='new', to='blog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='Фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фото новостей',
                'verbose_name_plural': 'Фото новостей',
            },
        ),
    ]
