# Generated by Django 5.2.4 on 2025-07-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='discription',
            new_name='description',
        ),
    ]
