# Generated by Django 5.2.4 on 2025-07-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_discription_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='image',
        ),
    ]
