# Generated by Django 5.2.4 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_newsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='Фото'),
        ),
    ]
