# Generated by Django 5.2.4 on 2025-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blog.tag', verbose_name='tags'),
        ),
    ]
