# Generated by Django 5.2.4 on 2025-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_news_name_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='new', to='blog.tag', verbose_name='tags'),
        ),
    ]
